os: osx
language: objective-c

osx_image: xcode10.2

podfile: UXSDKBetaSample/Podfile

before_install:
  - gem install cocoapods -v '1.7.0'
  - pod repo update

script: 
    - xcodebuild clean test -workspace UXSDKBetaSample/UXSDKBetaSample.xcworkspace -scheme UXSDKBetaSample -destination platform\=iOS\ Simulator,OS\=12.2,name\=iPad\ Pro\ \(9.7-inch\) CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
    - bundle exec danger
